import type { CatalogItem, LayoutTemplate, RoomSpec } from './contracts.js'

export const DEFAULT_ROOM: RoomSpec = {
  width: 24000,
  length: 12000,
  unit: 'mm',
}

export const CATALOG: CatalogItem[] = [
  {
    id: 's750',
    code: 'С750',
    name: 'Станок С750',
    family: 'saw',
    color: '#2563eb',
    width: 2200,
    length: 5000,
    safetyZone: 1200,
    aliases: ['с750', 's750', 'с-750'],
    analogs: ['topol'],
    description: 'Базовый распиловочный станок линии С750.',
  },
  {
    id: 'b700',
    code: 'Б700',
    name: 'Брусующий станок Б700',
    family: 'processing',
    color: '#0f766e',
    width: 1800,
    length: 3800,
    safetyZone: 1000,
    aliases: ['б700', 'b700'],
    analogs: ['m1000'],
    description: 'Брусующий станок для основного потока.',
  },
  {
    id: 'm1000',
    code: 'М1000',
    name: 'Многопил М1000',
    family: 'processing',
    color: '#7c3aed',
    width: 1900,
    length: 4200,
    safetyZone: 1000,
    aliases: ['м1000', 'm1000', 'миг', 'mig'],
    analogs: ['b700'],
    description: 'Многопильный блок / МИГ.',
  },
  {
    id: 'gs4',
    code: 'ГС4',
    name: 'Горбыльный станок ГС 4',
    family: 'finishing',
    color: '#dc2626',
    width: 1700,
    length: 3200,
    safetyZone: 900,
    aliases: ['гс4', 'гс 4', 'gs4'],
    analogs: [],
    description: 'Финишная операция линии.',
  },
  {
    id: 'nb',
    code: 'НБ',
    name: 'Накопитель бревен',
    family: 'input',
    color: '#f97316',
    width: 2600,
    length: 5200,
    safetyZone: 900,
    aliases: ['нб', 'накопитель бревен'],
    analogs: ['pb'],
    description: 'Входной накопитель бревен.',
  },
  {
    id: 'pb',
    code: 'ПБ',
    name: 'Подающий блок',
    family: 'input',
    color: '#ea580c',
    width: 2200,
    length: 4200,
    safetyZone: 850,
    aliases: ['пб', 'подающий блок'],
    analogs: ['nb'],
    description: 'Подающий узел перед станком.',
  },
  {
    id: 'vb',
    code: 'ВБ',
    name: 'Выравнивающий блок',
    family: 'input',
    color: '#f59e0b',
    width: 2000,
    length: 3600,
    safetyZone: 850,
    aliases: ['вб', 'выравнивающий блок'],
    analogs: ['vr'],
    description: 'Входной выравнивающий блок.',
  },
  {
    id: 'vr',
    code: 'ВР',
    name: 'Вальцовый рольганг ВР',
    family: 'transport',
    color: '#14b8a6',
    width: 1500,
    length: 4800,
    safetyZone: 700,
    aliases: ['вр', 'vr'],
    analogs: ['rolgang'],
    description: 'Транспортный участок линии.',
  },
  {
    id: 'vr-table',
    code: 'ВР-К',
    name: 'Стол-комплект ВР',
    family: 'transport',
    color: '#0ea5e9',
    width: 1600,
    length: 4200,
    safetyZone: 700,
    aliases: ['стол-комплект вр', 'стол комплект вр', 'вр комплект'],
    analogs: ['vr'],
    description: 'Комплект ВР для компактной схемы.',
  },
  {
    id: 'tcl',
    code: 'ТЦЛ',
    name: 'ТЦЛ',
    family: 'sorting',
    color: '#8b5cf6',
    width: 1800,
    length: 3600,
    safetyZone: 800,
    aliases: ['тцл', 'tcl'],
    analogs: ['tcp'],
    description: 'Транспортно-сортировочный участок.',
  },
  {
    id: 'tcp',
    code: 'ТЦП',
    name: 'ТЦП',
    family: 'sorting',
    color: '#a855f7',
    width: 1800,
    length: 3400,
    safetyZone: 800,
    aliases: ['тцп', 'tcp'],
    analogs: ['tcl'],
    description: 'Продольный транспортный участок.',
  },
  {
    id: 'rolgang',
    code: 'РГ',
    name: 'Рольганги',
    family: 'transport',
    color: '#0891b2',
    width: 1400,
    length: 4000,
    safetyZone: 650,
    aliases: ['рольганг', 'рольганги', 'ролганги', 'ролганг'],
    analogs: ['vr'],
    description: 'Рольганговый участок линии.',
  },
  {
    id: 'tonkomer',
    code: 'СТ',
    name: 'Станок для тонкомера',
    family: 'saw',
    color: '#2563eb',
    width: 2000,
    length: 4200,
    safetyZone: 1100,
    aliases: ['станок для тонкомера', 'тонкомер'],
    analogs: ['s750'],
    description: 'Отдельный станок под тонкомер.',
  },
  {
    id: 'topol',
    code: 'Тополь',
    name: 'Линия Тополь',
    family: 'saw',
    color: '#1d4ed8',
    width: 2400,
    length: 5200,
    safetyZone: 1200,
    aliases: ['тополь'],
    analogs: ['s750'],
    description: 'Аналог базовой пилорамы.',
  },
  {
    id: 'og',
    code: 'ОГ',
    name: 'Окантовочно-горбыльный участок',
    family: 'processing',
    color: '#b45309',
    width: 1800,
    length: 3200,
    safetyZone: 800,
    aliases: ['ог'],
    analogs: ['gs4'],
    description: 'Промежуточная обработка.',
  },
  {
    id: 'tgp',
    code: 'ТГП',
    name: 'ТГП',
    family: 'transport',
    color: '#0d9488',
    width: 1500,
    length: 3600,
    safetyZone: 700,
    aliases: ['тгп'],
    analogs: ['rolgang'],
    description: 'Потоковый транспортный модуль.',
  },
  {
    id: 'prsc',
    code: 'ПРСЦ',
    name: 'ПРСЦ',
    family: 'sorting',
    color: '#7c2d12',
    width: 1700,
    length: 3200,
    safetyZone: 800,
    aliases: ['прсц'],
    analogs: ['tcl'],
    description: 'Сортировочный узел.',
  },
  {
    id: 'grad',
    code: 'Град',
    name: 'Град',
    family: 'finishing',
    color: '#be185d',
    width: 1700,
    length: 3000,
    safetyZone: 850,
    aliases: ['град'],
    analogs: [],
    description: 'Финишный участок линии.',
  },
  {
    id: 'tkp',
    code: 'ТКП',
    name: 'ТКП',
    family: 'transport',
    color: '#475569',
    width: 1500,
    length: 3400,
    safetyZone: 700,
    aliases: ['ткп'],
    analogs: ['rolgang'],
    description: 'Транспортный завершающий модуль.',
  },
]

export const TEMPLATES: LayoutTemplate[] = [
  {
    id: 's750-standard',
    name: 'С750 стандарт',
    description: 'Базовая стандартная линия без автоматизации.',
    suggestedRoom: DEFAULT_ROOM,
    sequence: ['nb', 's750', 'rolgang', 'b700', 'm1000', 'gs4'],
    allowedFamilies: ['input', 'saw', 'transport', 'processing', 'finishing'],
    spacingX: 1800,
    spacingY: 1600,
    paddingX: 1500,
    paddingY: 1500,
  },
  {
    id: 's750-automation',
    name: 'С750 с автоматизацией',
    description: 'Линия С750 с подачей, транспортом и сортировкой.',
    suggestedRoom: DEFAULT_ROOM,
    sequence: ['nb', 'pb', 'vr', 's750', 'tcl', 'tcp', 'rolgang', 'b700', 'm1000'],
    allowedFamilies: ['input', 'transport', 'saw', 'sorting', 'processing'],
    spacingX: 1700,
    spacingY: 1600,
    paddingX: 1400,
    paddingY: 1400,
  },
  {
    id: 'tonkomer-compact',
    name: 'Тонкомер компакт',
    description: 'Компактная схема для тонкомера.',
    suggestedRoom: {
      width: 18000,
      length: 10000,
      unit: 'mm',
    },
    sequence: ['vr-table', 'tonkomer', 'tcl', 'b700', 'rolgang'],
    allowedFamilies: ['transport', 'saw', 'sorting', 'processing'],
    spacingX: 1500,
    spacingY: 1500,
    paddingX: 1200,
    paddingY: 1200,
  },
  {
    id: 'yard-preproject',
    name: 'Уличный предварительный проект',
    description: 'Расширенная линия из реального примера.',
    suggestedRoom: {
      width: 28000,
      length: 14000,
      unit: 'mm',
    },
    sequence: ['nb', 'pb', 'vb', 'topol', 'og', 'tgp', 'm1000', 'prsc', 'grad', 'tkp'],
    allowedFamilies: ['input', 'saw', 'transport', 'processing', 'sorting', 'finishing'],
    spacingX: 1800,
    spacingY: 1800,
    paddingX: 1500,
    paddingY: 1500,
  },
]

export const AI_FEW_SHOTS = [
  {
    input: 'стандартная комплектация без автоматизации со станками: С750 Б700 М1000 ГС 4',
    templateId: 's750-standard',
    itemIds: ['s750', 'b700', 'm1000', 'gs4'],
  },
  {
    input: 'Поставить: НБ ПБ ВР С-750 ТЦЛ ТЦП Б700 рольганги М1000',
    templateId: 's750-automation',
    itemIds: ['nb', 'pb', 'vr', 's750', 'tcl', 'tcp', 'b700', 'rolgang', 'm1000'],
  },
  {
    input: 'поставить: стол-комплект Вр станок для тонкомера ТЦЛ Б700 рольганги',
    templateId: 'tonkomer-compact',
    itemIds: ['vr-table', 'tonkomer', 'tcl', 'b700', 'rolgang'],
  },
]

export const STOPWORDS = new Set([
  'поставить',
  'стандартная',
  'комплектация',
  'без',
  'автоматизации',
  'со',
  'станками',
  'также',
  'так',
  'же',
  'метра',
  'метров',
  'метр',
  'пока',
  'будет',
  'будут',
  'сделать',
  'предварительный',
  'проект',
  'длина',
  'бревен',
  'бревна',
  'дуб',
  'для',
  'и',
  'или',
  'на',
  'в',
  'по',
  'как',
  'что',
  'из',
  'под',
  'новый',
])

export function getCatalogItem(catalogId: string) {
  return CATALOG.find((item) => item.id === catalogId) ?? null
}

export function getTemplate(templateId: string | null | undefined) {
  if (!templateId) {
    return null
  }

  return TEMPLATES.find((template) => template.id === templateId) ?? null
}
